### ISSUE TITLE
Peer review of iplimit for tagged version 1.0 (upcoming)

### ISSUE THREAD

**Issue by gdestuynder** [mozilla/irc-iplimit#1]
@gdestuynder to review [tag 1.0](https://github.com/mozilla/irc-iplimit/tree/7e0779938e6ca942221545187d53decd983258e1)

**Comment by gdestuynder** [comment]
Will start when tag for 1.0 is comit'd  (@danparson)

**Comment by danparsons** [comment]
My final changes are in and 1.0 has been tagged

**Comment by gdestuynder** [comment]
Created https://github.com/mozilla/irc-iplimit/pull/4 from empty branch for review purposes, will track work there.
